// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solve_lower_bidiagonal
Rcpp::NumericVector solve_lower_bidiagonal(const Rcpp::NumericVector& a, const Rcpp::NumericVector& l, const Rcpp::NumericVector& b);
RcppExport SEXP _dynclusts_solve_lower_bidiagonal(SEXP aSEXP, SEXP lSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type l(lSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_lower_bidiagonal(a, l, b));
    return rcpp_result_gen;
END_RCPP
}
// solve_upper_bidiagonal
Rcpp::NumericVector solve_upper_bidiagonal(const Rcpp::NumericVector& a, const Rcpp::NumericVector& u, const Rcpp::NumericVector& b);
RcppExport SEXP _dynclusts_solve_upper_bidiagonal(SEXP aSEXP, SEXP uSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_upper_bidiagonal(a, u, b));
    return rcpp_result_gen;
END_RCPP
}
// logdens_psi
Eigen::VectorXf logdens_psi(const float psi, const float H1T1, const float sum_e1T, const float sum_e_mid, const float sum_e_dif);
RcppExport SEXP _dynclusts_logdens_psi(SEXP psiSEXP, SEXP H1T1SEXP, SEXP sum_e1TSEXP, SEXP sum_e_midSEXP, SEXP sum_e_difSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const float >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const float >::type H1T1(H1T1SEXP);
    Rcpp::traits::input_parameter< const float >::type sum_e1T(sum_e1TSEXP);
    Rcpp::traits::input_parameter< const float >::type sum_e_mid(sum_e_midSEXP);
    Rcpp::traits::input_parameter< const float >::type sum_e_dif(sum_e_difSEXP);
    rcpp_result_gen = Rcpp::wrap(logdens_psi(psi, H1T1, sum_e1T, sum_e_mid, sum_e_dif));
    return rcpp_result_gen;
END_RCPP
}
// logdens_varphi
Eigen::VectorXf logdens_varphi(const float varphi, const float logdet_K_check, const Eigen::MatrixXf K_check_inv, const Eigen::MatrixXf K_check, const Eigen::MatrixXf D, const Eigen::VectorXf gamm, const float tau2, const float a_phi, const float b_phi);
RcppExport SEXP _dynclusts_logdens_varphi(SEXP varphiSEXP, SEXP logdet_K_checkSEXP, SEXP K_check_invSEXP, SEXP K_checkSEXP, SEXP DSEXP, SEXP gammSEXP, SEXP tau2SEXP, SEXP a_phiSEXP, SEXP b_phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const float >::type varphi(varphiSEXP);
    Rcpp::traits::input_parameter< const float >::type logdet_K_check(logdet_K_checkSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type K_check_inv(K_check_invSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type K_check(K_checkSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXf >::type gamm(gammSEXP);
    Rcpp::traits::input_parameter< const float >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< const float >::type a_phi(a_phiSEXP);
    Rcpp::traits::input_parameter< const float >::type b_phi(b_phiSEXP);
    rcpp_result_gen = Rcpp::wrap(logdens_varphi(varphi, logdet_K_check, K_check_inv, K_check, D, gamm, tau2, a_phi, b_phi));
    return rcpp_result_gen;
END_RCPP
}
// dnormal
Eigen::ArrayXXd dnormal(const Eigen::ArrayXXd& y, const Eigen::ArrayXXd& mu, const double sigma2);
RcppExport SEXP _dynclusts_dnormal(SEXP ySEXP, SEXP muSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::ArrayXXd& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2(sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(dnormal(y, mu, sigma2));
    return rcpp_result_gen;
END_RCPP
}
// haver_dist
Rcpp::NumericMatrix haver_dist(Rcpp::NumericMatrix& coords);
RcppExport SEXP _dynclusts_haver_dist(SEXP coordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    rcpp_result_gen = Rcpp::wrap(haver_dist(coords));
    return rcpp_result_gen;
END_RCPP
}
// int_sampling
Rcpp::IntegerVector int_sampling(const int& K, const int& num_samples, const Rcpp::NumericVector& probs);
RcppExport SEXP _dynclusts_int_sampling(SEXP KSEXP, SEXP num_samplesSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const int& >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(int_sampling(K, num_samples, probs));
    return rcpp_result_gen;
END_RCPP
}
// int_sampling_rows
Rcpp::IntegerVector int_sampling_rows(const Rcpp::NumericMatrix& probs_mat);
RcppExport SEXP _dynclusts_int_sampling_rows(SEXP probs_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type probs_mat(probs_matSEXP);
    rcpp_result_gen = Rcpp::wrap(int_sampling_rows(probs_mat));
    return rcpp_result_gen;
END_RCPP
}
// lambda_ratio_log_l
double lambda_ratio_log_l(const Eigen::VectorXd& center_lambda, const Eigen::MatrixXd& cov_lambda);
RcppExport SEXP _dynclusts_lambda_ratio_log_l(SEXP center_lambdaSEXP, SEXP cov_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type center_lambda(center_lambdaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type cov_lambda(cov_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_ratio_log_l(center_lambda, cov_lambda));
    return rcpp_result_gen;
END_RCPP
}
// rand_mvnorm
Eigen::VectorXf rand_mvnorm(const Eigen::MatrixXf& precision_matrix, const Eigen::VectorXf& parameter_vector);
RcppExport SEXP _dynclusts_rand_mvnorm(SEXP precision_matrixSEXP, SEXP parameter_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXf& >::type precision_matrix(precision_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXf& >::type parameter_vector(parameter_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(rand_mvnorm(precision_matrix, parameter_vector));
    return rcpp_result_gen;
END_RCPP
}
// rand_mvnorm_db
Eigen::VectorXd rand_mvnorm_db(const Eigen::MatrixXd& precision_matrix, const Eigen::VectorXd& parameter_vector);
RcppExport SEXP _dynclusts_rand_mvnorm_db(SEXP precision_matrixSEXP, SEXP parameter_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type precision_matrix(precision_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type parameter_vector(parameter_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(rand_mvnorm_db(precision_matrix, parameter_vector));
    return rcpp_result_gen;
END_RCPP
}
// optimize_moment_matching
double optimize_moment_matching(double c, double l);
RcppExport SEXP _dynclusts_optimize_moment_matching(SEXP cSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_moment_matching(c, l));
    return rcpp_result_gen;
END_RCPP
}
// rand_polya_proposal
Eigen::MatrixXd rand_polya_proposal(const Eigen::VectorXd& a_vec, const Eigen::VectorXd& b_vec, const Eigen::VectorXd& lambda_vec);
RcppExport SEXP _dynclusts_rand_polya_proposal(SEXP a_vecSEXP, SEXP b_vecSEXP, SEXP lambda_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type a_vec(a_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type b_vec(b_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambda_vec(lambda_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(rand_polya_proposal(a_vec, b_vec, lambda_vec));
    return rcpp_result_gen;
END_RCPP
}
// row_unique_counts
Rcpp::IntegerVector row_unique_counts(Rcpp::NumericMatrix mat);
RcppExport SEXP _dynclusts_row_unique_counts(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(row_unique_counts(mat));
    return rcpp_result_gen;
END_RCPP
}
// NumVec_to_EigenVec
Eigen::VectorXd NumVec_to_EigenVec(Rcpp::NumericVector& x);
RcppExport SEXP _dynclusts_NumVec_to_EigenVec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(NumVec_to_EigenVec(x));
    return rcpp_result_gen;
END_RCPP
}
// NumVec_to_EigenVec_float
Eigen::VectorXf NumVec_to_EigenVec_float(const Rcpp::NumericVector& x);
RcppExport SEXP _dynclusts_NumVec_to_EigenVec_float(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(NumVec_to_EigenVec_float(x));
    return rcpp_result_gen;
END_RCPP
}
// chol_float
Eigen::MatrixXf chol_float(const Eigen::MatrixXf& M);
RcppExport SEXP _dynclusts_chol_float(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXf& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(chol_float(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynclusts_solve_lower_bidiagonal", (DL_FUNC) &_dynclusts_solve_lower_bidiagonal, 3},
    {"_dynclusts_solve_upper_bidiagonal", (DL_FUNC) &_dynclusts_solve_upper_bidiagonal, 3},
    {"_dynclusts_logdens_psi", (DL_FUNC) &_dynclusts_logdens_psi, 5},
    {"_dynclusts_logdens_varphi", (DL_FUNC) &_dynclusts_logdens_varphi, 9},
    {"_dynclusts_dnormal", (DL_FUNC) &_dynclusts_dnormal, 3},
    {"_dynclusts_haver_dist", (DL_FUNC) &_dynclusts_haver_dist, 1},
    {"_dynclusts_int_sampling", (DL_FUNC) &_dynclusts_int_sampling, 3},
    {"_dynclusts_int_sampling_rows", (DL_FUNC) &_dynclusts_int_sampling_rows, 1},
    {"_dynclusts_lambda_ratio_log_l", (DL_FUNC) &_dynclusts_lambda_ratio_log_l, 2},
    {"_dynclusts_rand_mvnorm", (DL_FUNC) &_dynclusts_rand_mvnorm, 2},
    {"_dynclusts_rand_mvnorm_db", (DL_FUNC) &_dynclusts_rand_mvnorm_db, 2},
    {"_dynclusts_optimize_moment_matching", (DL_FUNC) &_dynclusts_optimize_moment_matching, 2},
    {"_dynclusts_rand_polya_proposal", (DL_FUNC) &_dynclusts_rand_polya_proposal, 3},
    {"_dynclusts_row_unique_counts", (DL_FUNC) &_dynclusts_row_unique_counts, 1},
    {"_dynclusts_NumVec_to_EigenVec", (DL_FUNC) &_dynclusts_NumVec_to_EigenVec, 1},
    {"_dynclusts_NumVec_to_EigenVec_float", (DL_FUNC) &_dynclusts_NumVec_to_EigenVec_float, 1},
    {"_dynclusts_chol_float", (DL_FUNC) &_dynclusts_chol_float, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynclusts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
