# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_lower_bidiagonal <- function(a, l, b) {
    .Call('_dynclusts_solve_lower_bidiagonal', PACKAGE = 'dynclusts', a, l, b)
}

solve_upper_bidiagonal <- function(a, u, b) {
    .Call('_dynclusts_solve_upper_bidiagonal', PACKAGE = 'dynclusts', a, u, b)
}

logdens_psi <- function(psi, H1T1, sum_e1T, sum_e_mid, sum_e_dif) {
    .Call('_dynclusts_logdens_psi', PACKAGE = 'dynclusts', psi, H1T1, sum_e1T, sum_e_mid, sum_e_dif)
}

logdens_varphi <- function(varphi, logdet_K_check, K_check_inv, K_check, D, gamm, tau2, a_phi, b_phi) {
    .Call('_dynclusts_logdens_varphi', PACKAGE = 'dynclusts', varphi, logdet_K_check, K_check_inv, K_check, D, gamm, tau2, a_phi, b_phi)
}

dnormal_disjoint <- function(y, mu, sigma2) {
    .Call('_dynclusts_dnormal_disjoint', PACKAGE = 'dynclusts', y, mu, sigma2)
}

dnormal_joint <- function(y, mu, sigma2) {
    .Call('_dynclusts_dnormal_joint', PACKAGE = 'dynclusts', y, mu, sigma2)
}

haver_dist <- function(coords) {
    .Call('_dynclusts_haver_dist', PACKAGE = 'dynclusts', coords)
}

int_sampling <- function(K, num_samples, probs) {
    .Call('_dynclusts_int_sampling', PACKAGE = 'dynclusts', K, num_samples, probs)
}

int_sampling_rows <- function(probs_mat) {
    .Call('_dynclusts_int_sampling_rows', PACKAGE = 'dynclusts', probs_mat)
}

lambda_ratio_log_l <- function(center_lambda, cov_lambda) {
    .Call('_dynclusts_lambda_ratio_log_l', PACKAGE = 'dynclusts', center_lambda, cov_lambda)
}

rand_mvnorm <- function(precision_matrix, parameter_vector) {
    .Call('_dynclusts_rand_mvnorm', PACKAGE = 'dynclusts', precision_matrix, parameter_vector)
}

rand_mvnorm_db <- function(precision_matrix, parameter_vector) {
    .Call('_dynclusts_rand_mvnorm_db', PACKAGE = 'dynclusts', precision_matrix, parameter_vector)
}

optimize_moment_matching <- function(c, l) {
    .Call('_dynclusts_optimize_moment_matching', PACKAGE = 'dynclusts', c, l)
}

rand_polya_proposal <- function(a_vec, b_vec, lambda_vec) {
    .Call('_dynclusts_rand_polya_proposal', PACKAGE = 'dynclusts', a_vec, b_vec, lambda_vec)
}

row_unique_counts <- function(mat) {
    .Call('_dynclusts_row_unique_counts', PACKAGE = 'dynclusts', mat)
}

NumVec_to_EigenVec <- function(x) {
    .Call('_dynclusts_NumVec_to_EigenVec', PACKAGE = 'dynclusts', x)
}

NumVec_to_EigenVec_float <- function(x) {
    .Call('_dynclusts_NumVec_to_EigenVec_float', PACKAGE = 'dynclusts', x)
}

chol_float <- function(M) {
    .Call('_dynclusts_chol_float', PACKAGE = 'dynclusts', M)
}

